### ISSUE TITLE
Rare AssertionError in Python interface

### ISSUE THREAD

**Issue by arosen93** [snurr-group/mofid#24]
The Python interface crashes for the following CIF: [mof.txt](https://github.com/snurr-group/mofid/files/3693935/mof.txt). The web interface works fine. Need to fix assertion statement.

Traceback:
```
==============================
*** Open Babel Error  in WriteSystre
  Found two neighboring 2-c sites.  Flagging the cgd output to get an error instead of the incorrect topology.
Note: Rerun ExportSystre() with simplify_two_conn=false if an unsimplified net is useful.
==============================
*** Open Babel Error  in WriteSystre
  Found two neighboring 2-c sites.  Flagging the cgd output to get an error instead of the incorrect topology.
Note: Rerun ExportSystre() with simplify_two_conn=false if an unsimplified net is useful.
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    mofid = cif2mofid(cif_path)
  File "C:\Users\asros\Anaconda3\lib\site-packages\mofid\run_mofid.py", line 24, in cif2mofid
    'SingleNode','topology.cgd'))
  File "C:\Users\asros\Anaconda3\lib\site-packages\mofid\id_constructor.py", line 134, in extract_topology
    assert line[-2] == str(current_component)
AssertionError
```

**Comment by YOUNG-JAME** [comment]
Open Babel Error  in WriteSystre
Found two neighboring 2-c sites.  Flagging the cgd output to get an error instead of the incorrect topology.
Note: Rerun ExportSystre() with simplify_two_conn=false if an unsimplified net is useful.
——————————————————————————————————————————————————
Can you tell me what this error means in terms of molecular structure? Is there any solution？

**Comment by bbucior** [comment]
For this structure, MOFid ran into an unexpected topology when attempting to deconstruct it into building blocks. It's been awhile since working with the code, but my guess would be either (a) something with assigning bond lengths, (b) a metal note connecting to two points instead of more (e.g., if you had a copper paddlewheel with only two points of contact instead of four, then an organic linker only connected to the paddlewheel and one other component), or (c) a structure that the code is not yet able to process correctly.

My main advice for debugging would be visualizing the generated CIFs in the Output/ directory (specifically Output/SingleNode and Output/AllNode), either in your favorite visualization tool or the [web-mofid UI](https://snurr-group.github.io/web-mofid/sbu.html). I used to flip between the Nodes + Linkers and the Simplified Topology views to see how the MOFid code was interpreting the structure and understand what chemistry was leading to the code assigning a pair of 2-coordinated neighbors.
