### ISSUE TITLE
'Unknown' and 'NA' topologies on CoRE MOF dataset

### ISSUE THREAD

**Issue by NegaNexus** [snurr-group/mofid#26]
When running the CoRE MOF dataset through mofid, I get an issue with about a third of them being labeled with `'UNKNOWN'` or `'NA'` topology. Specifically:
- 27.9% are of `'UNKNOWN'` topology
- 6.9% are of `'NA'` topology

I have tried to do some digging to resolve the issue, but I have yet to find a lead. For reference, here is a [JSON](https://github.com/snurr-group/mofid/files/4961467/mofids.json.zip) file of the Python dictionaries generated for each MOF in the dataset. Any ideas what could be causing this?

**Comment by arosen93** [comment]
@NegaNexus: 

Thank you for reaching out. MOFid attempts to resolve the topology using [Systre](http://gavrog.org/), which pulls from the list of topologies on the [RCSR](http://rcsr.anu.edu.au/). A description of the messages you have received is in the Supporting Information of the original [MOFid paper](https://pubs.acs.org/doi/suppl/10.1021/acs.cgd.9b01050/suppl_file/cg9b01050_si_001.pdf).

An instance of `UNKNOWN` indicates that a topology was successfully parsed, but no topology code has been assigned for it on the RCSR. Since there is no topology code, we currently have no option but to assign it an `UKNOWN` label. Currently, MOFid is using the RCSR data as of June 1, 2019, which is the most recent public release, as noted [here](http://rcsr.anu.edu.au/systre). If and when a new version of the RCSR database is made available for download (or if you would like to modify the file to introduce new topology codes), that can be done by modifying the [RCSRnets.arc file](https://github.com/snurr-group/mofid/tree/master/Resources) and recompiling MOFid. If a topology is labeled as 'NA', there was some issue with parsing the topology, usually an instance that the topology is not well-defined (no MOF net detected). This can happen, for instance, if a material is not actually a MOF and has no underlying topology, but there are other possible reasons (e.g. if the `sbu.cpp` code crashes).

With the original MOFid paper, we have made all the MOFid/MOFkeys available for the CoRE MOF database (for all MOFs that were available at the time of writing). You can find them in the Supporting Information [here](https://pubs.acs.org/doi/suppl/10.1021/acs.cgd.9b01050/suppl_file/cg9b01050_si_002.zip). You should see that the distributions are similar to what you have independently reported.

Please let me know if you have any other questions.
