### ISSUE TITLE
Clarification on Handling Allnode Topology in Web vs. Local Run in mofid

### ISSUE THREAD

**Issue by Xuwznln** [snurr-group/mofid#32]
Hello, I'm currently exploring the use of mofid and I have a question about its behavior on different platform (Web and Local Run). I observed that when running locally, mofid processes allnode topology and generates identifiers in the form of sn,an. However, this doesn't seem to be the case when running on a web run.
When aiming to compare whether two MOFs are identical, should the an (allnode) parameter be included to ensure accurate comparison?

**Comment by bbucior** [comment]
Could you please share a small example CIF? I tried to reproduce this issue using one of the [example MOFs](https://github.com/snurr-group/mofid/blob/master/Resources/TestCIFs/nbob_sym_5_mc_2_sym_5_on_13_L_16.cif), but it shows the full `nbo,fof` on the web version. I'm not seeing anything obvious in the [JS code](https://github.com/snurr-group/web-mofid/blob/master/sbu.html#L103) for the sn,an formatting, either. Perhaps something is happening during MOF/topology analysis.

**Comment by Xuwznln** [comment]
Hi, I rechecked some mofs with sn,an formatting, finding that the only difference is showing TIMEOUT. I re-run the local mofid and got the same result with web mofid. Does it mean if all TIMEOUT mofs need re-run to ensure the result? And here is the example cif. Thanks!
[example_cif.txt](https://github.com/snurr-group/mofid/files/15213488/example_cif.txt)

**Comment by bbucior** [comment]
That's the general idea--it's just a user-facing error message to flag a closer look. By default, the Systre command is set with a soft timeout [limit of 30 seconds](https://github.com/snurr-group/mofid/blob/master/Python/id_constructor.py#L40) (adjustable or rerunnable). Without that limit imposed, it was difficult to run high-throughput screening on large MOF databases, since the topology detection could take an unreasonable amount of time or fail to run on a small handful of structures (enormous unit cells, poorly deconstructed geometry, etc.).

**Comment by Xuwznln** [comment]
I'll separate the timeout MOFs and re-run them with a more generous time limit. Thanks for your explanation!
